#!/usr/bin/env python3
"""AI-Lore Claude binding — contract reinforcement hooks (generated by ai-lore.py install).
pre : PreToolUse on Write/Edit — denies edits to existing journal entries (journal-append-forward).
post: PostToolUse on Write/Edit — reminds the session of the golden rule (advisory)."""
import json, os, re, sys
mode = sys.argv[1] if len(sys.argv) > 1 else "pre"
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
path = (d.get("tool_input") or {}).get("file_path") or ""
JOURNAL = re.compile(r"/journal/(live|archive)/\d{4}-\d{2}-\d{2}_\d+\.md$")
if mode == "pre":
    if JOURNAL.search(path) and os.path.exists(path):
        print(json.dumps({"hookSpecificOutput": {"hookEventName": "PreToolUse", "permissionDecision": "deny",
              "permissionDecisionReason": "AI-Lore contract journal-append-forward: journal entries are never edited after writing. Record corrections in this session's own entry instead."}}))
else:
    print(json.dumps({"hookSpecificOutput": {"hookEventName": "PostToolUse",
          "additionalContext": "AI-Lore golden rule: this write belongs to a verb the Human Lead confirmed — name it if you have not. Nothing writes unchosen."}}))
sys.exit(0)
